Fix ambiguous `log` import (#64)
Otherwise it may conflict with the one imported from esp_idf_sys.

```
error[E0659]: `log` is ambiguous
 --> /esp-idf-svc-0.39.1/src/sntp.rs:4:5
  |
4 | use log::*;
  |     ^^^ ambiguous name
  |
  = note: ambiguous because of multiple potential import sources
  = note: `log` could refer to a crate passed with `--extern`
  = help: use `::log` to refer to this crate unambiguously
note: `log` could also refer to the struct imported here
 --> /esp-idf-svc-0.39.1/src/sntp.rs:8:5
  |
8 | use esp_idf_sys::*;
  |     ^^^^^^^^^^^^^^
  = help: use `self::log` to refer to this struct unambiguously

For more information about this error, try `rustc --explain E0659`.
```